networks:
  app-network:
    driver: bridge

services:
  posts:
    container_name: posts
    restart: unless-stopped
    build:
      context: ./post-service
      dockerfile: deploy/Dockerfile
      network: host
    env_file: './post-service/.env'
    ports:
      - ${POSTSERVICE_PORT}:${POSTSERVICE_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:18
    env_file: './post-service/.env'
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    restart: unless-stopped
    build:
      context: ./api-gateway
      dockerfile: deploy/Dockerfile
      network: host
    env_file: './api-gateway/.env'
    ports:
      - ${APIGATEWAY_PORT}:${APIGATEWAY_PORT}
    depends_on:
      - posts
    networks:
      - app-network

  auth:
    container_name: auth
    restart: unless-stopped
    build:
      context: ./auth-service
      dockerfile: deploy/Dockerfile
      network: host
    env_file: './auth-service/.env'
    ports:
      - ${AUTHSERVICE_PORT}:${AUTHSERVICE_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local