// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gfdmit/web-forum/post-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateBoard provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateBoard(ctx context.Context, input model.CreateBoardInput) (model.Board, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBoard")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateBoardInput) (model.Board, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateBoardInput) model.Board); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateBoardInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBoard'
type MockRepository_CreateBoard_Call struct {
	*mock.Call
}

// CreateBoard is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.CreateBoardInput
func (_e *MockRepository_Expecter) CreateBoard(ctx interface{}, input interface{}) *MockRepository_CreateBoard_Call {
	return &MockRepository_CreateBoard_Call{Call: _e.mock.On("CreateBoard", ctx, input)}
}

func (_c *MockRepository_CreateBoard_Call) Run(run func(ctx context.Context, input model.CreateBoardInput)) *MockRepository_CreateBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateBoardInput
		if args[1] != nil {
			arg1 = args[1].(model.CreateBoardInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateBoard_Call) Return(board model.Board, err error) *MockRepository_CreateBoard_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockRepository_CreateBoard_Call) RunAndReturn(run func(ctx context.Context, input model.CreateBoardInput) (model.Board, error)) *MockRepository_CreateBoard_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateComment(ctx context.Context, input model.CreateCommentInput) (model.Comment, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 model.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateCommentInput) (model.Comment, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateCommentInput) model.Comment); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(model.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateCommentInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockRepository_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.CreateCommentInput
func (_e *MockRepository_Expecter) CreateComment(ctx interface{}, input interface{}) *MockRepository_CreateComment_Call {
	return &MockRepository_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, input)}
}

func (_c *MockRepository_CreateComment_Call) Run(run func(ctx context.Context, input model.CreateCommentInput)) *MockRepository_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateCommentInput
		if args[1] != nil {
			arg1 = args[1].(model.CreateCommentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateComment_Call) Return(comment model.Comment, err error) *MockRepository_CreateComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockRepository_CreateComment_Call) RunAndReturn(run func(ctx context.Context, input model.CreateCommentInput) (model.Comment, error)) *MockRepository_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePost provides a mock function for the type MockRepository
func (_mock *MockRepository) CreatePost(ctx context.Context, input model.CreatePostInput) (model.Post, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 model.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreatePostInput) (model.Post, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreatePostInput) model.Post); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(model.Post)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreatePostInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockRepository_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.CreatePostInput
func (_e *MockRepository_Expecter) CreatePost(ctx interface{}, input interface{}) *MockRepository_CreatePost_Call {
	return &MockRepository_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, input)}
}

func (_c *MockRepository_CreatePost_Call) Run(run func(ctx context.Context, input model.CreatePostInput)) *MockRepository_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreatePostInput
		if args[1] != nil {
			arg1 = args[1].(model.CreatePostInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreatePost_Call) Return(post model.Post, err error) *MockRepository_CreatePost_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockRepository_CreatePost_Call) RunAndReturn(run func(ctx context.Context, input model.CreatePostInput) (model.Post, error)) *MockRepository_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBoard provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteBoard(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBoard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBoard'
type MockRepository_DeleteBoard_Call struct {
	*mock.Call
}

// DeleteBoard is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) DeleteBoard(ctx interface{}, id interface{}) *MockRepository_DeleteBoard_Call {
	return &MockRepository_DeleteBoard_Call{Call: _e.mock.On("DeleteBoard", ctx, id)}
}

func (_c *MockRepository_DeleteBoard_Call) Run(run func(ctx context.Context, id int)) *MockRepository_DeleteBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteBoard_Call) Return(err error) *MockRepository_DeleteBoard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteBoard_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_DeleteBoard_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteComment(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) DeleteComment(ctx interface{}, id interface{}) *MockRepository_DeleteComment_Call {
	return &MockRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, id)}
}

func (_c *MockRepository_DeleteComment_Call) Run(run func(ctx context.Context, id int)) *MockRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteComment_Call) Return(err error) *MockRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePost provides a mock function for the type MockRepository
func (_mock *MockRepository) DeletePost(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockRepository_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) DeletePost(ctx interface{}, id interface{}) *MockRepository_DeletePost_Call {
	return &MockRepository_DeletePost_Call{Call: _e.mock.On("DeletePost", ctx, id)}
}

func (_c *MockRepository_DeletePost_Call) Run(run func(ctx context.Context, id int)) *MockRepository_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeletePost_Call) Return(err error) *MockRepository_DeletePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeletePost_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetBoard provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBoard(ctx context.Context, id int) (model.Board, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBoard")
	}

	var r0 model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Board, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Board); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Board)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoard'
type MockRepository_GetBoard_Call struct {
	*mock.Call
}

// GetBoard is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetBoard(ctx interface{}, id interface{}) *MockRepository_GetBoard_Call {
	return &MockRepository_GetBoard_Call{Call: _e.mock.On("GetBoard", ctx, id)}
}

func (_c *MockRepository_GetBoard_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetBoard_Call) Return(board model.Board, err error) *MockRepository_GetBoard_Call {
	_c.Call.Return(board, err)
	return _c
}

func (_c *MockRepository_GetBoard_Call) RunAndReturn(run func(ctx context.Context, id int) (model.Board, error)) *MockRepository_GetBoard_Call {
	_c.Call.Return(run)
	return _c
}

// GetBoards provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBoards(ctx context.Context, includeDeleted bool) ([]model.Board, error) {
	ret := _mock.Called(ctx, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for GetBoards")
	}

	var r0 []model.Board
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]model.Board, error)); ok {
		return returnFunc(ctx, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []model.Board); ok {
		r0 = returnFunc(ctx, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Board)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBoards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBoards'
type MockRepository_GetBoards_Call struct {
	*mock.Call
}

// GetBoards is a helper method to define mock.On call
//   - ctx context.Context
//   - includeDeleted bool
func (_e *MockRepository_Expecter) GetBoards(ctx interface{}, includeDeleted interface{}) *MockRepository_GetBoards_Call {
	return &MockRepository_GetBoards_Call{Call: _e.mock.On("GetBoards", ctx, includeDeleted)}
}

func (_c *MockRepository_GetBoards_Call) Run(run func(ctx context.Context, includeDeleted bool)) *MockRepository_GetBoards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetBoards_Call) Return(boards []model.Board, err error) *MockRepository_GetBoards_Call {
	_c.Call.Return(boards, err)
	return _c
}

func (_c *MockRepository_GetBoards_Call) RunAndReturn(run func(ctx context.Context, includeDeleted bool) ([]model.Board, error)) *MockRepository_GetBoards_Call {
	_c.Call.Return(run)
	return _c
}

// GetComment provides a mock function for the type MockRepository
func (_mock *MockRepository) GetComment(ctx context.Context, id int) (model.Comment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetComment")
	}

	var r0 model.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Comment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Comment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComment'
type MockRepository_GetComment_Call struct {
	*mock.Call
}

// GetComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetComment(ctx interface{}, id interface{}) *MockRepository_GetComment_Call {
	return &MockRepository_GetComment_Call{Call: _e.mock.On("GetComment", ctx, id)}
}

func (_c *MockRepository_GetComment_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetComment_Call) Return(comment model.Comment, err error) *MockRepository_GetComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockRepository_GetComment_Call) RunAndReturn(run func(ctx context.Context, id int) (model.Comment, error)) *MockRepository_GetComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockRepository
func (_mock *MockRepository) GetComments(ctx context.Context, postID int, includeDeleted bool, limit int, offset int) ([]model.Comment, error) {
	ret := _mock.Called(ctx, postID, includeDeleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []model.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool, int, int) ([]model.Comment, error)); ok {
		return returnFunc(ctx, postID, includeDeleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool, int, int) []model.Comment); ok {
		r0 = returnFunc(ctx, postID, includeDeleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool, int, int) error); ok {
		r1 = returnFunc(ctx, postID, includeDeleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int
//   - includeDeleted bool
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) GetComments(ctx interface{}, postID interface{}, includeDeleted interface{}, limit interface{}, offset interface{}) *MockRepository_GetComments_Call {
	return &MockRepository_GetComments_Call{Call: _e.mock.On("GetComments", ctx, postID, includeDeleted, limit, offset)}
}

func (_c *MockRepository_GetComments_Call) Run(run func(ctx context.Context, postID int, includeDeleted bool, limit int, offset int)) *MockRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_GetComments_Call) Return(comments []model.Comment, err error) *MockRepository_GetComments_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *MockRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, postID int, includeDeleted bool, limit int, offset int) ([]model.Comment, error)) *MockRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetPost provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPost(ctx context.Context, id int) (model.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 model.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Post)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPost'
type MockRepository_GetPost_Call struct {
	*mock.Call
}

// GetPost is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetPost(ctx interface{}, id interface{}) *MockRepository_GetPost_Call {
	return &MockRepository_GetPost_Call{Call: _e.mock.On("GetPost", ctx, id)}
}

func (_c *MockRepository_GetPost_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetPost_Call) Return(post model.Post, err error) *MockRepository_GetPost_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockRepository_GetPost_Call) RunAndReturn(run func(ctx context.Context, id int) (model.Post, error)) *MockRepository_GetPost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosts provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPosts(ctx context.Context, boardID int, includeDeleted bool, limit int, offset int) ([]model.Post, error) {
	ret := _mock.Called(ctx, boardID, includeDeleted, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPosts")
	}

	var r0 []model.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool, int, int) ([]model.Post, error)); ok {
		return returnFunc(ctx, boardID, includeDeleted, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool, int, int) []model.Post); ok {
		r0 = returnFunc(ctx, boardID, includeDeleted, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool, int, int) error); ok {
		r1 = returnFunc(ctx, boardID, includeDeleted, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosts'
type MockRepository_GetPosts_Call struct {
	*mock.Call
}

// GetPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID int
//   - includeDeleted bool
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) GetPosts(ctx interface{}, boardID interface{}, includeDeleted interface{}, limit interface{}, offset interface{}) *MockRepository_GetPosts_Call {
	return &MockRepository_GetPosts_Call{Call: _e.mock.On("GetPosts", ctx, boardID, includeDeleted, limit, offset)}
}

func (_c *MockRepository_GetPosts_Call) Run(run func(ctx context.Context, boardID int, includeDeleted bool, limit int, offset int)) *MockRepository_GetPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_GetPosts_Call) Return(posts []model.Post, err error) *MockRepository_GetPosts_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockRepository_GetPosts_Call) RunAndReturn(run func(ctx context.Context, boardID int, includeDeleted bool, limit int, offset int) ([]model.Post, error)) *MockRepository_GetPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProfile(ctx context.Context, userID int) (model.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (model.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) model.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockRepository_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockRepository_GetProfile_Call {
	return &MockRepository_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockRepository_GetProfile_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProfile_Call) Return(profile model.Profile, err error) *MockRepository_GetProfile_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockRepository_GetProfile_Call) RunAndReturn(run func(ctx context.Context, userID int) (model.Profile, error)) *MockRepository_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfiles provides a mock function for the type MockRepository
func (_mock *MockRepository) GetProfiles(ctx context.Context, includeDeleted bool) ([]model.Profile, error) {
	ret := _mock.Called(ctx, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for GetProfiles")
	}

	var r0 []model.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]model.Profile, error)); ok {
		return returnFunc(ctx, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []model.Profile); ok {
		r0 = returnFunc(ctx, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfiles'
type MockRepository_GetProfiles_Call struct {
	*mock.Call
}

// GetProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - includeDeleted bool
func (_e *MockRepository_Expecter) GetProfiles(ctx interface{}, includeDeleted interface{}) *MockRepository_GetProfiles_Call {
	return &MockRepository_GetProfiles_Call{Call: _e.mock.On("GetProfiles", ctx, includeDeleted)}
}

func (_c *MockRepository_GetProfiles_Call) Run(run func(ctx context.Context, includeDeleted bool)) *MockRepository_GetProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetProfiles_Call) Return(profiles []model.Profile, err error) *MockRepository_GetProfiles_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *MockRepository_GetProfiles_Call) RunAndReturn(run func(ctx context.Context, includeDeleted bool) ([]model.Profile, error)) *MockRepository_GetProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreBoard provides a mock function for the type MockRepository
func (_mock *MockRepository) RestoreBoard(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreBoard")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RestoreBoard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreBoard'
type MockRepository_RestoreBoard_Call struct {
	*mock.Call
}

// RestoreBoard is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) RestoreBoard(ctx interface{}, id interface{}) *MockRepository_RestoreBoard_Call {
	return &MockRepository_RestoreBoard_Call{Call: _e.mock.On("RestoreBoard", ctx, id)}
}

func (_c *MockRepository_RestoreBoard_Call) Run(run func(ctx context.Context, id int)) *MockRepository_RestoreBoard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RestoreBoard_Call) Return(err error) *MockRepository_RestoreBoard_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RestoreBoard_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockRepository_RestoreBoard_Call {
	_c.Call.Return(run)
	return _c
}
